// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn: typeof import('./components/common/buttons/Btn.vue')['default']
    Countdown: typeof import('./components/home/Countdown.vue')['default']
    EventInfo: typeof import('./components/home/EventInfo.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    HomeHero: typeof import('./components/home/HomeHero.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    JoinUs: typeof import('./components/home/JoinUs.vue')['default']
    Nav: typeof import('./components/common/nav/Nav.vue')['default']
    NavRoute: typeof import('./components/common/nav/NavRoute.vue')['default']
    PrimaryBtn: typeof import('./components/common/buttons/PrimaryBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RSVPBtn: typeof import('./components/common/buttons/RSVPBtn.vue')['default']
  }
}
